/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package AAAREE;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author emili
 */
public class FormAgregarUsuario extends javax.swing.JDialog {

    /**
     * Creates new form FormAgregarUsuario
     */
    public FormAgregarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setTitle("Formulario para AGREGAR USUARIO");
        getContentPane().setBackground(new java.awt.Color(153, 255, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombre = new javax.swing.JLabel();
        LabelApellidoP = new javax.swing.JLabel();
        LabelApellidoM = new javax.swing.JLabel();
        LabelTelefono = new javax.swing.JLabel();
        TxtFieldNombre = new javax.swing.JTextField();
        TxtFieldApellidoP = new javax.swing.JTextField();
        TxtFieldApellidoM = new javax.swing.JTextField();
        TxtFieldTelefono = new javax.swing.JTextField();
        ButtonGuardar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setForeground(new java.awt.Color(204, 255, 153));

        LabelNombre.setText("Nombre(s)");

        LabelApellidoP.setText("Apellido Paterno");

        LabelApellidoM.setText("Apellido Materno");

        LabelTelefono.setText("Número Telefónico");

        ButtonGuardar.setText("Guardar");
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelTelefono)
                    .addComponent(LabelApellidoM)
                    .addComponent(LabelApellidoP)
                    .addComponent(LabelNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtFieldApellidoM)
                    .addComponent(TxtFieldApellidoP)
                    .addComponent(TxtFieldNombre)
                    .addComponent(TxtFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonGuardar)
                .addGap(18, 18, 18)
                .addComponent(ButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(TxtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellidoP)
                    .addComponent(TxtFieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellidoM)
                    .addComponent(TxtFieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTelefono)
                    .addComponent(TxtFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancelar)
                    .addComponent(ButtonGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
        ButtonCancelar.addActionListener(e -> {
            TxtFieldNombre.setText("");
            TxtFieldApellidoP.setText("");
            TxtFieldApellidoM.setText("");
            TxtFieldTelefono.setText("");
            this.dispose();
        });
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        if (TxtFieldNombre.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "El campo NOMBRE no puede estar vacío, por favor ingrese un nombre válido",
                "Error de validación",
                JOptionPane.ERROR_MESSAGE
        );
    } else {
        String UsuarioNombre = TxtFieldNombre.getText();
        String UsuarioApellidoP = TxtFieldApellidoP.getText();
        String UsuarioApellidoM = TxtFieldApellidoM.getText();
        String UsuarioTelefono = TxtFieldTelefono.getText();

        ConectorBD co = new ConectorBD();
        int Respuesta = co.CreateUsuario(UsuarioNombre, UsuarioApellidoP, UsuarioApellidoM, UsuarioTelefono);

        if (Respuesta == 1) {
            String[] opciones = {"Agregar Otro Usuario", "Salir"};
            int seleccion = JOptionPane.showOptionDialog(
                    this,
                    "Registro de usuario completado.\n¿Qué te gustaría hacer a continuación?",
                    "¡Usuario Agregado!",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    opciones,
                    opciones[0]
            );

            // Manejar la selección del usuario
            if (seleccion == JOptionPane.YES_OPTION) {
                // Opción "Agregar Otro Usuario": Limpiar campos y mantener el formulario abierto
                TxtFieldNombre.setText("");
                TxtFieldApellidoP.setText("");
                TxtFieldApellidoM.setText("");
                TxtFieldTelefono.setText("");
            } else if (seleccion == JOptionPane.NO_OPTION) {
                // Opción "Salir": Cerrar el formulario
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Registro fallido",
                    "No se ha podido agregar el usuario",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAgregarUsuario dialog = new FormAgregarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JLabel LabelApellidoM;
    private javax.swing.JLabel LabelApellidoP;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JTextField TxtFieldApellidoM;
    private javax.swing.JTextField TxtFieldApellidoP;
    private javax.swing.JTextField TxtFieldNombre;
    private javax.swing.JTextField TxtFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
